# Auto-generated by tools/gen_cdfsod_configs.py -- DO NOT EDIT BY HAND.
# Regenerate with:  python tools/gen_cdfsod_configs.py
#
# Dataset : ArTaxOr
# Shot    : 1-shot
# Variant : ets
# ---------------------------------------------------------------------
_base_ = ['../_base_ets.py']

data_root = '../datasets/ArTaxOr/'
metainfo = dict(classes=('Araneae', 'Coleoptera', 'Diptera', 'Hemiptera', 'Hymenoptera', 'Lepidoptera', 'Odonata'))
train_ann_file = 'annotations/1_shot.json'
num_classes = 7

# Override placeholders defined in _base_ets.py
train_dataloader = dict(
    dataset=dict(
        data_root=data_root,
        ann_file=train_ann_file,
        metainfo=metainfo))

val_dataloader = dict(
    dataset=dict(data_root=data_root, metainfo=metainfo))
test_dataloader = val_dataloader

val_evaluator = dict(ann_file=data_root + 'annotations/test.json')
test_evaluator = val_evaluator

model = dict(bbox_head=dict(num_classes=7))

# work_dir mirrors CDFSOD-benchmark/main_results.sh layout:
#   output/<variant>/<dataset>_<shot>shot/
work_dir = 'work_dirs/cdfsod/ets/artaxor_1shot'
