# Auto-generated by tools/gen_cdfsod_configs.py -- DO NOT EDIT BY HAND.
# Regenerate with:  python tools/gen_cdfsod_configs.py
#
# Dataset : NEU-DET
# Shot    : 5-shot
# Variant : baseline
# ---------------------------------------------------------------------
_base_ = ['../_base_baseline.py']

data_root = '../datasets/NEU-DET/'
metainfo = dict(classes=('crazing', 'inclusion', 'patches', 'pitted_surface', 'rolled-in_scale', 'scratches'))
train_ann_file = 'annotations/5_shot.json'
num_classes = 6

# Override placeholders defined in _base_baseline.py
train_dataloader = dict(
    dataset=dict(
        data_root=data_root,
        ann_file=train_ann_file,
        metainfo=metainfo))

val_dataloader = dict(
    dataset=dict(data_root=data_root, metainfo=metainfo))
test_dataloader = val_dataloader

val_evaluator = dict(ann_file=data_root + 'annotations/test.json')
test_evaluator = val_evaluator

model = dict(bbox_head=dict(num_classes=6))

# work_dir mirrors CDFSOD-benchmark/main_results.sh layout:
#   output/<variant>/<dataset>_<shot>shot/
work_dir = 'work_dirs/cdfsod/baseline/neu-det_5shot'
