"""Generate the 36 CD-FSOD leaf configs for ETS benchmark experiments.

For every (dataset, shot, variant) combination this script produces a
small leaf config under ``configs/cdfsod/<dataset>/<shot>shot_<variant>.py``
that inherits from the corresponding ``_base_<variant>.py`` and
overrides only:
    - data_root
    - metainfo
    - train_ann_file
    - num_classes (model.bbox_head)
    - work_dir output path

Run from repo root:
    python tools/gen_cdfsod_configs.py
"""
import os
import sys

# Make the configs package importable as a normal Python module so we
# can read the canonical dataset metadata defined in
# configs/cdfsod/_dataset_meta.py
HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(REPO, 'configs', 'cdfsod'))

import _dataset_meta as meta  # noqa: E402

LEAF_TEMPLATE = '''\
# Auto-generated by tools/gen_cdfsod_configs.py -- DO NOT EDIT BY HAND.
# Regenerate with:  python tools/gen_cdfsod_configs.py
#
# Dataset : {ds_name}
# Shot    : {shot}-shot
# Variant : {variant}
# ---------------------------------------------------------------------
_base_ = ['../_base_{variant}.py']

data_root = '{data_root}'
metainfo = dict(classes={classes!r})
train_ann_file = 'annotations/{shot}_shot.json'
num_classes = {num_classes}

# Override placeholders defined in _base_{variant}.py
train_dataloader = dict(
    dataset=dict(
        data_root=data_root,
        ann_file=train_ann_file,
        metainfo=metainfo))

val_dataloader = dict(
    dataset=dict(data_root=data_root, metainfo=metainfo))
test_dataloader = val_dataloader

val_evaluator = dict(ann_file=data_root + 'annotations/test.json')
test_evaluator = val_evaluator

model = dict({extra_model})

# work_dir mirrors CDFSOD-benchmark/main_results.sh layout:
#   output/<variant>/<dataset>_<shot>shot/
work_dir = 'work_dirs/cdfsod/{variant}/{dataset_key}_{shot}shot'
'''

VARIANTS = ('baseline', 'ets', 'vpe')


def _model_overrides(variant: str, dataset_key: str, shot: int,
                     num_classes: int) -> str:
    """Return the comma-separated kwargs that fill `model = dict({...})`.

    The VPE variant additionally points at the dataset-specific support
    feature bundle that ``tools/build_support_features.py`` is expected
    to have produced under ``support_features/``.
    """
    parts = [f'bbox_head=dict(num_classes={num_classes})']
    if variant == 'vpe':
        # Path is relative to mmdetection/ (where tools/train.py is
        # launched from), matching the existing convention used by
        # ``data_root = '../datasets/...'``.  build_support_features.py
        # writes to ``ETS/support_features/`` so a single ``../`` is
        # the correct number of levels.
        sf_path = (
            f"'../support_features/{dataset_key}_{shot}shot.pt'"
        )
        parts.append(f'support_features_path={sf_path}')
    return ', '.join(parts)


def render(dataset_key: str, info: dict, shot: int, variant: str) -> str:
    return LEAF_TEMPLATE.format(
        ds_name=info['name'],
        shot=shot,
        variant=variant,
        data_root=info['data_root'],
        classes=info['classes'],
        num_classes=len(info['classes']),
        dataset_key=dataset_key,
        extra_model=_model_overrides(
            variant, dataset_key, shot, len(info['classes'])),
    )


def main() -> None:
    out_root = os.path.join(REPO, 'configs', 'cdfsod')
    n_written = 0
    for ds_key, info in meta.DATASETS.items():
        for shot in meta.SHOTS:
            for variant in VARIANTS:
                out_dir = os.path.join(out_root, ds_key)
                os.makedirs(out_dir, exist_ok=True)
                out_path = os.path.join(
                    out_dir, f'{shot}shot_{variant}.py')
                with open(out_path, 'w', encoding='utf-8') as f:
                    f.write(render(ds_key, info, shot, variant))
                n_written += 1
    print(f'[gen_cdfsod_configs] wrote {n_written} leaf configs '
          f'into {out_root} (variants={list(VARIANTS)})')


if __name__ == '__main__':
    main()
