# Auto-generated by tools/gen_cdfsod_configs.py -- DO NOT EDIT BY HAND.
# Regenerate with:  python tools/gen_cdfsod_configs.py
#
# Dataset : DIOR
# Shot    : 10-shot
# Variant : vpe
# ---------------------------------------------------------------------
_base_ = ['../_base_vpe.py']

data_root = '../datasets/DIOR/'
metainfo = dict(classes=('Expressway-Service-area', 'Expressway-toll-station', 'airplane', 'airport', 'baseballfield', 'basketballcourt', 'bridge', 'chimney', 'dam', 'golffield', 'groundtrackfield', 'harbor', 'overpass', 'ship', 'stadium', 'storagetank', 'tenniscourt', 'trainstation', 'vehicle', 'windmill'))
train_ann_file = 'annotations/10_shot.json'
num_classes = 20

# Override placeholders defined in _base_vpe.py
train_dataloader = dict(
    dataset=dict(
        data_root=data_root,
        ann_file=train_ann_file,
        metainfo=metainfo))

val_dataloader = dict(
    dataset=dict(data_root=data_root, metainfo=metainfo))
test_dataloader = val_dataloader

val_evaluator = dict(ann_file=data_root + 'annotations/test.json')
test_evaluator = val_evaluator

model = dict(bbox_head=dict(num_classes=20), support_features_path='../support_features/dior_10shot.pt')

# work_dir mirrors CDFSOD-benchmark/main_results.sh layout:
#   output/<variant>/<dataset>_<shot>shot/
work_dir = 'work_dirs/cdfsod/vpe/dior_10shot'
